from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import (
    EmployerViewSet, PositionViewSet, UserViewSet, employer_login, employer_signup, get_leave_management, payroll_calculation, payroll_details, unverified_users, update_leave_status, update_user_verification, user_detail, user_list, user_login,user_signup, verified_users,get_approved_leaves,get_pending_leaves,get_rejected_leaves,loss_pay
)
from payroll_app import views

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'Employers', EmployerViewSet)
router.register(r'Position', PositionViewSet)

urlpatterns = [

    path('signup-apis/user-signup/', user_signup, name='user_signup'),
    path('login-apis/users-login/', views.user_login, name='user_login'),
    path('signup-apis/employer-signup/', employer_signup, name='employer_signup'),
    path('login-apis/employers-login/', employer_login, name='employer_login'),

    path('verfication-apis/unverified/', unverified_users, name='unverified-users'),
    path('verfication-apis/verified/', verified_users, name='unverified-users'),
    path('verfication-apis/update-verification/<int:user_id>/', views.update_user_verification, name='update_user_verification'),

    path('leave-apis/leave-apply/', views.leave_apply, name='leave-apply'),
    path('leave-apis/loss_pay/', views.loss_pay, name='loss_pay'),

    path('api/positions/create/', views.position_create, name='position_create'),
    path('api/positions/update/<int:pk>/', views.position_update, name='position_update'),

    path('employers/update_leave_status/<int:user_id>/', update_leave_status),
    
    path('api/leave-management/', get_leave_management, name='get_leave_management'),
    path('api/get-pending-leaves/', views.get_pending_leaves, name='get_pending_leaves'),
    path('api/get-approved-leaves/', views.get_approved_leaves, name='get_approved_leaves'),
    path('api/get-rejected-leaves/',get_rejected_leaves, name='get_rejected_leaves'),   
    path('payroll-calculation/', views.payroll_calculation, name='payroll-calculation'),
    path('user/payroll-details/<int:user_id>/',payroll_details),
    path('user-annual-salary-revision/<int:user_id>/', views.user_annual_salary_revision, name='user_annual_salary_revision'),
    path('users/<int:id>/salary/', views.user_salary, name='user_salary'),

]

# Add the URLs generated by the router
urlpatterns += router.urls